language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.6"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database aera_test;' -U postgres